spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: xyx020717
    driver-class-name: com.mysql.cj.jdbc.Driver  #8.0以上需要cj

    druid:
      aop-patterns: com.bc.springboot.* #spring监控的aop切入点,该包下的所有文件接收监控
      filters: stat,wall #配置开启什么监控组件(开启了防火墙和sql监控)

      #监控页的配置
      stat-view-servlet:
        enabled: true #默认为false,所以想要什么功能都需要写入配置文件进行开启
        login-username: zsb
        login-password: xyx020717
        reset-enable: false #禁用重置按钮(禁用后点击重置无效)

      #监控web应用(URL监控,web应用监控)
      web-stat-filter:
        enabled: true
        url-pattern: /* #匹配拿些路径
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      #对已开启监控功能的详细配置
      filter:
        stat:
          slow-sql-millis: 1000 #慢查询设置:只要查询超过1000ms,都为慢查询
          log-slow-sql: true #是否用日志记录慢查询
          enabled: true #开启sql监控功能
        wall:
          enabled: true #开启防火墙功能
          config:
            drop-table-allow: false #拦截所有删表操作





  #    type: com.zaxxer.hikari.HikariDataSource #默认类型为HikariDataSource,不用配置
  jdbc:
    template:
      query-timeout: 3 #超时时间,3s内没操作成功视为超时(修改JdbcTemplateConfiguration.class中的template.getQueryTimeout())

